# Site settings
title: Much to learn
email: 
description: > # this means to ignore newlines until "baseurl:"
  Hello! I'm Leon.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://leontian.github.io" # the base hostname & protocol for your site
github_username: leontian
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# Build settings
markdown: kramdown

theme: jekyll-theme-hacker