# Site settings
title: Much to learn
email: 
description: You still have
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://leontian.github.io" # the base hostname & protocol for your site
github_username: leontian
# Build settings
markdown: kramdown

theme: jekyll-theme-hacker
